StylesPath = styles
MinAlertLevel = suggestion

Packages = proselint, write-good

Vocab = Blog

[*.md]
BasedOnStyles = Vale, proselint, write-good
# Skip Hugo shortcodes
BlockIgnores = (?s)\{\{[<%].*?[%>]\}\}
# Skip Hugo front matter
TokenIgnores = (?s)^\+\+\+.*?\+\+\+
